Fixed prefix issue with conda build.
    -json was failing in the package build.sh with:
        TypeError: the JSON object must be str, not 'bytes'
    -the gpirc can get in the way of building a clean package so
        an 'ignore-gpirc' option was added.